// Generated by LiveScript 1.4.0
(function(){
  module.exports = function(str){
    var p, urlencode, form2json, arr, keys, values, obj, ref$;
    p = require('prelude-ls');
    urlencode = require('urlencode');
    form2json = require('form2json');
    arr = str.split(/'([^']+)'/);
    keys = arr.filter(function(item, index){
      return p.even(index);
    }).map(function(it){
      return it.trim();
    });
    values = arr.filter(function(item, index){
      return p.odd(index);
    }).map(function(it){
      return it.trim();
    });
    obj = p.zip(keys, values);
    return {
      method: obj.find(function(it){
        return it[0] === '--data';
      }) != null ? 'POST' : 'GET',
      url: obj.find(function(it){
        return it[0] === 'curl';
      })[1],
      headers: p.pairsToObj(
      p.map(function(it){
        return it[1].split(": ");
      })(
      p.filter(function(it){
        return it[0] === '-H';
      })(
      obj))),
      formData: form2json.decode((ref$ = obj.find(function(it){
        return it[0] === '--data';
      })) != null ? ref$[1] : void 8)
    };
  };
}).call(this);
